--------------POST_OF_PARTNERS
--SCHEMA
--POST_ID
--USER_ID
--USER_NAME
--DESCRIPTION
--POST_IMAGE
--TRACK_CODE
--UPLOAD_DATE
--FIRST_NAME
--LAST_NAME
--USER_IMAGE
--EMAIL

CREATE PROCEDURE ALL_POST_OF_PARTNERS 
AS
SELECT dbo.POSTS.POST_ID, dbo.POSTS.USER_ID, dbo.USERS.USER_NAME,
		dbo.POSTS.DESCRIPTION, dbo.POSTS.POST_IMAGE, dbo.POSTS.TRACK_CODE,
		dbo.POSTS.UPLOAD_DATE, dbo.USERS.FIRST_NAME, dbo.USERS.LAST_NAME, 
        dbo.USERS.USER_IMAGE, dbo.USERS.EMAIL

FROM     dbo.POSTS INNER JOIN  dbo.USERS ON dbo.POSTS.USER_ID = dbo.USERS.USER_ID

--EXEC ALL_POST_OF_PARTNERS


CREATE PROCEDURE POST_OF_PARTNERS_BY_USER @USER_ID_OUT int
AS
SELECT DISTINCT dbo.POSTS.POST_ID, dbo.POSTS.USER_ID, dbo.POSTS.DESCRIPTION,
		dbo.POSTS.POST_IMAGE, dbo.POSTS.TRACK_CODE, dbo.POSTS.UPLOAD_DATE,
		dbo.USERS.USER_NAME, dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME, 
        dbo.USERS.LAST_NAME, dbo.USERS.USER_IMAGE
FROM     dbo.USERS INNER JOIN dbo.POSTS ON dbo.USERS.USER_ID = dbo.POSTS.USER_ID
			CROSS JOIN dbo.DESTINATIONS
WHERE @USER_ID_OUT = dbo.POSTS.USER_ID

--EXEC POST_OF_PARTNERS_BY_USER 1









----------------------------------RECOMMENDATIONS
--SCHEMA
--RECO_ID
--USER_ID
--DESTINATION_CODE
--DESCRIPTION
--POST_IMAGE
--UPLOAD_DATE
--USER_NAME
--EMAIL
--FIRST_NAME
--LAST_NAME
--USER_IMAGE
--DESTINATION_NAME

CREATE PROCEDURE  ALL_RECOMMENDATIONS
AS
SELECT DISTINCT	dbo.RECOMMENDATIONS.RECO_ID, dbo.RECOMMENDATIONS.USER_ID,
		dbo.RECOMMENDATIONS.[DESTINATION_CODE],
		dbo.RECOMMENDATIONS.DESCRIPTION, dbo.RECOMMENDATIONS.POST_IMAGE,
		dbo.RECOMMENDATIONS.UPLOAD_DATE, dbo.USERS.USER_NAME, 
        dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME, dbo.USERS.LAST_NAME,
		dbo.USERS.USER_IMAGE, dbo.DESTINATIONS.DESCRIPTION AS [DESTINATION_NAME]
FROM     dbo.RECOMMENDATIONS INNER JOIN dbo.USERS ON dbo.RECOMMENDATIONS.USER_ID = dbo.USERS.USER_ID
		INNER JOIN  dbo.DESTINATIONS ON dbo.RECOMMENDATIONS.DESTINATION_CODE = dbo.DESTINATIONS.DESTINATION_CODE

EXEC  ALL_RECOMMENDATIONS



CREATE PROCEDURE  RECOMMENDATIONS_BY_DESTINATION @DESTINATION_CODE_OUT int
AS
SELECT DISTINCT dbo.RECOMMENDATIONS.RECO_ID, dbo.RECOMMENDATIONS.USER_ID,
		dbo.RECOMMENDATIONS.[DESTINATION_CODE],
		dbo.RECOMMENDATIONS.DESCRIPTION, dbo.RECOMMENDATIONS.POST_IMAGE,
		dbo.RECOMMENDATIONS.UPLOAD_DATE, dbo.USERS.USER_NAME, 
        dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME, dbo.USERS.LAST_NAME,
		dbo.USERS.USER_IMAGE, dbo.DESTINATIONS.DESCRIPTION AS [DESTINATION_NAME]
FROM     dbo.DESTINATIONS INNER JOIN dbo.RECOMMENDATIONS ON dbo.DESTINATIONS.DESTINATION_CODE = dbo.RECOMMENDATIONS.DESTINATION_CODE
		INNER JOIN dbo.USERS ON dbo.RECOMMENDATIONS.USER_ID = dbo.USERS.USER_ID
WHERE @DESTINATION_CODE_OUT = [dbo].[RECOMMENDATIONS].[DESTINATION_CODE]

--EXEC RECOMMENDATIONS_BY_DESTINATION 1



-------------------------------TRACKS
--SCHEMA
--TRACK_CODE
--USER_ID
--DESCRIPTION
--ACTIVE
--TRACK_LOACTIONS
--USER_NAME
--EMAIL
--FIRST_NAME
--LAST_NAME
--USER_IMAGE
CREATE PROC ALL_TRACKS
AS
SELECT dbo.TRACKS.TRACK_CODE, dbo.TRACKS.USER_ID,
	   dbo.TRACKS.DESCRIPTION, dbo.TRACKS.ACTIVE,
	   dbo.TRACKS.TRACK_LOACTIONS, dbo.USERS.USER_NAME,
	   dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME,
	   dbo.USERS.LAST_NAME, dbo.USERS.USER_IMAGE
FROM   dbo.TRACKS INNER JOIN dbo.USERS ON dbo.TRACKS.USER_ID = dbo.USERS.USER_ID

EXEC ALL_TRACKS



CREATE PROC ALL_TRACKS_BY_DESTINATION @DESTINATION_OUT int
AS
SELECT DISTINCT dbo.TRACKS.TRACK_CODE, dbo.TRACKS.USER_ID,
	   dbo.TRACKS.DESCRIPTION, dbo.TRACKS.ACTIVE,
	   dbo.TRACKS.TRACK_LOACTIONS, dbo.USERS.USER_NAME,
	   dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME,
	   dbo.USERS.LAST_NAME, dbo.USERS.USER_IMAGE
FROM   dbo.TRACKS INNER JOIN dbo.USERS ON dbo.TRACKS.USER_ID = dbo.USERS.USER_ID
WHERE TRACK_LOACTIONS LIKE '%destinationCode__' + CAST(@DESTINATION_OUT AS varchar)  + '%';

EXEC ALL_TRACKS_BY_DESTINATION 1


CREATE PROC ALL_TRACKS_BY_USER @USER_ID_OUT int
AS
SELECT DISTINCT dbo.TRACKS.TRACK_CODE, dbo.TRACKS.USER_ID,
	   dbo.TRACKS.DESCRIPTION, dbo.TRACKS.ACTIVE,
	   dbo.TRACKS.TRACK_LOACTIONS, dbo.USERS.USER_NAME,
	   dbo.USERS.EMAIL, dbo.USERS.FIRST_NAME,
	   dbo.USERS.LAST_NAME, dbo.USERS.USER_IMAGE
FROM   dbo.TRACKS INNER JOIN dbo.USERS ON dbo.TRACKS.USER_ID = dbo.USERS.USER_ID
WHERE dbo.TRACKS.USER_ID = @USER_ID_OUT

EXEC ALL_TRACKS_BY_USER 2